# Generated by Django 4.2.21 on 2025-05-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
